(function (root, factory) {
  var data = factory();
  if (typeof module === 'object' && module.exports) module.exports = data;
  root.PARALLEL_WORLDS_INSIGHTS = data;
}(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

  function insight(id, start, end, trackIds, ru, en, zh, sourceIds) {
    return {
      id: id,
      start: start,
      end: end,
      trackIds: trackIds,
      copy: {
        ru: { title: ru[0], summary: ru[1] },
        en: { title: en[0], summary: en[1] },
        zh: { title: zh[0], summary: zh[1] }
      },
      sourceIds: sourceIds
    };
  }

  return [
    insight('gobekli-jomon', -9600, -8200, ['gobekli-tepe', 'jomon'],
      ['Гёбекли-Тепе и ранний Дзёмон', 'Монументальные комплексы Верхней Месопотамии создавались в те тысячелетия, когда сообщества Японского архипелага уже пользовались керамикой. Это сопоставление времени, а не свидетельство контакта.'],
      ['Göbekli Tepe and early Jōmon', 'Monumental enclosures were built in Upper Mesopotamia during millennia when communities in the Japanese archipelago already used pottery. This compares chronology; it does not imply contact.'],
      ['哥贝克力石阵与早期绳纹', '上美索不达米亚建造纪念性建筑群的数千年间，日本列岛社群已在使用陶器。这只是年代对照，并不意味着彼此接触。'], ['unesco-gobekli-2018', 'met-jomon-2002']),
    insight('catalhoyuk-mehrgarh', -7000, -6200, ['catalhoyuk', 'mehrgarh'],
      ['Чатал-Хююк и Мергарх', 'Плотно застроенное поселение Чатал-Хююк существовало одновременно с ранней производящей экономикой и последующей поселенческой последовательностью Мергарха.'],
      ['Çatalhöyük and Mehrgarh', 'Çatalhöyük’s densely built settlement overlapped with early food production and the continuing settlement sequence at Mehrgarh.'],
      ['恰塔霍裕克与梅尔伽赫', '恰塔霍裕克的密集聚落与梅尔伽赫的早期食物生产及其持续聚落序列在年代上重叠。'], ['unesco-catalhoyuk-2012', 'kenoyer-indus-2011']),
    insight('liangzhu-uruk', -3300, -3100, ['liangzhu', 'uruk'],
      ['Лянчжу и Урук', 'Городской комплекс Лянчжу в низовьях Янцзы и крупный центр Урука в южной Месопотамии существовали в пересекающихся хронологических рамках. Их устройство и источниковая база различны.'],
      ['Liangzhu and Uruk', 'The Liangzhu urban complex in the lower Yangtze and the major center of Uruk in southern Mesopotamia occupied overlapping chronological frames. Their organization and evidence differ.'],
      ['良渚与乌鲁克', '长江下游的良渚城市综合体与美索不达米亚南部的乌鲁克大型中心在年代上有所重叠；两者的社会组织与证据基础并不相同。'], ['unesco-liangzhu-2019', 'met-uruk-2003']),
    insight('sumer-egypt-cities', -2900, -2700, ['sumer', 'egypt'],
      ['Шумерские города-государства и ранний Египет', 'Раннединастические города южной Месопотамии существовали в те же века, когда вдоль Нила укреплялось раннее государство.'],
      ['Sumerian city-states and early Egypt', 'Early Dynastic cities in southern Mesopotamia existed while an early state consolidated along the Nile.'],
      ['苏美尔城邦与早期埃及', '美索不达米亚南部的早王朝城市与尼罗河沿岸早期国家的巩固处于同一时代。'], ['met']),
    insight('akkad-indus-networks', -2340, -2150, ['akkadia', 'indus'],
      ['Аккад и города Инда', 'Территориальная держава Аккада существовала рядом по времени с развитой городской сетью Хараппской цивилизации.'],
      ['Akkad and the Indus cities', 'Akkad’s territorial state overlapped in time with the mature urban network of the Harappan civilization.'],
      ['阿卡德与印度河城市', '阿卡德的领土国家与成熟哈拉帕文明的城市网络在时间上彼此重叠。'], ['met']),
    insight('babylon-egypt-bronze', -1800, -1650, ['babylonia', 'egypt'],
      ['Хаммурапи и Среднее царство', 'Старовавилонская учёность развивалась в эпоху, когда Египет проходил поздние этапы Среднего царства.'],
      ['Hammurabi and the Middle Kingdom', 'Old Babylonian scholarship developed while Egypt was passing through the later Middle Kingdom.'],
      ['汉谟拉比与中王国', '古巴比伦的学术传统发展之时，埃及正处于中王国的后期阶段。'], ['met']),
    insight('hittites-new-kingdom', -1500, -1200, ['hittites', 'egypt'],
      ['Хетты и Новое царство', 'Хеттская держава и египетское Новое царство были современниками и соперниками восточного Средиземноморья.'],
      ['Hittites and the New Kingdom', 'The Hittite state and Egypt’s New Kingdom were contemporaries and rivals in the eastern Mediterranean.'],
      ['赫梯与新王国', '赫梯国家与埃及新王国同处一个时代，也是东地中海世界的竞争者。'], ['met']),
    insight('assyria-greece', -700, -609, ['assyria', 'greece'],
      ['Ассирия и архаическая Греция', 'Новоассирийская империя достигла расцвета тогда, когда в Греции формировались архаические полисы.'],
      ['Assyria and Archaic Greece', 'The Neo-Assyrian Empire flourished while the poleis of Archaic Greece were taking shape.'],
      ['亚述与古风希腊', '新亚述帝国繁荣之时，古风时期的希腊城邦也正在形成。'], ['met']),
    insight('confucius-greek-polis', -551, -480, ['confucianism', 'greece'],
      ['Конфуций и греческие полисы', 'Учение Конфуция складывалось в Китае в ту же эпоху, когда греческие полисы развивали собственные политические и философские традиции.'],
      ['Confucius and the Greek poleis', 'Confucius taught in China while the Greek poleis developed their own political and philosophical traditions.'],
      ['孔子与希腊城邦', '孔子在中国传授思想之时，希腊城邦也在发展各自的政治与哲学传统。'], ['asia', 'met']),
    insight('persia-greek-world', -550, -330, ['persia', 'greece'],
      ['Персия и греческий мир', 'Держава Ахеменидов и греческие полисы развивались в общей восточносредиземноморской системе конфликтов и обмена.'],
      ['Persia and the Greek world', 'The Achaemenid state and the Greek poleis developed within one eastern Mediterranean system of conflict and exchange.'],
      ['波斯与希腊世界', '阿契美尼德国家与希腊城邦处在同一个充满冲突与交流的东地中海体系中。'], ['met']),
    insight('buddhism-achaemenids', -500, -330, ['buddhism', 'persia'],
      ['Ранний буддизм и Ахемениды', 'Первые буддийские общины возникали в Южной Азии, пока Ахеменидская держава связывала огромные пространства Западной и Центральной Азии.'],
      ['Early Buddhism and the Achaemenids', 'The first Buddhist communities emerged in South Asia while the Achaemenid state connected vast parts of West and Central Asia.'],
      ['早期佛教与阿契美尼德', '最初的佛教社群在南亚出现时，阿契美尼德国家正连接西亚与中亚的广阔区域。'], ['asia', 'met']),
    insight('rome-han-china', -221, 220, ['rome', 'china'],
      ['Рим и Ханьский Китай', 'Римская республика и империя существовали одновременно с объединённым Китаем Цинь и Хань на противоположных концах Евразии.'],
      ['Rome and Han China', 'The Roman Republic and Empire overlapped with the unified Qin and Han states at the opposite end of Eurasia.'],
      ['罗马与汉代中国', '罗马共和国及帝国与欧亚大陆另一端统一的秦汉国家处于同一时代。'], ['met', 'asia']),
    insight('maya-roman-world', -200, 476, ['maya', 'rome'],
      ['Майя и Рим', 'Города майя развивались в Мезоамерике на протяжении столетий, которые в Средиземноморье относятся к римской эпохе.'],
      ['The Maya and Rome', 'Maya cities developed in Mesoamerica across centuries that belong to the Roman era in the Mediterranean.'],
      ['玛雅与罗马', '玛雅城市在中部美洲发展的数百年，正对应地中海世界的罗马时代。'], ['smarthistory', 'met']),
    insight('aksum-rome', -100, 476, ['ethiopia', 'rome'],
      ['Аксум и Рим', 'Аксумское царство участвовало в торговле Красного моря в те же века, когда Рим господствовал в Средиземноморье.'],
      ['Aksum and Rome', 'The kingdom of Aksum participated in Red Sea trade while Rome dominated the Mediterranean.'],
      ['阿克苏姆与罗马', '阿克苏姆王国参与红海贸易之时，罗马正主导地中海世界。'], ['british', 'met']),
    insight('christianity-buddhist-asia', 30, 600, ['christianity', 'buddhism'],
      ['Христианство и буддийская Азия', 'Ранние христианские общины распространялись по Римскому миру, пока буддийские школы и монастыри расширялись по Азии.'],
      ['Christianity and Buddhist Asia', 'Early Christian communities spread through the Roman world while Buddhist schools and monasteries expanded across Asia.'],
      ['基督教与佛教亚洲', '早期基督徒社群在罗马世界传播之时，佛教宗派与寺院也在亚洲扩展。'], ['met', 'asia']),
    insight('byzantium-tang', 618, 900, ['byzantium', 'china'],
      ['Византия и Танский Китай', 'Константинополь и столицы Тан были центрами двух сложных имперских миров на разных концах Евразии.'],
      ['Byzantium and Tang China', 'Constantinople and the Tang capitals anchored two sophisticated imperial worlds at opposite ends of Eurasia.'],
      ['拜占庭与唐代中国', '君士坦丁堡与唐代都城分别支撑着欧亚大陆两端复杂的帝国世界。'], ['met', 'asia']),
    insight('islam-tang', 618, 750, ['islam', 'china'],
      ['Ранний ислам и империя Тан', 'Мусульманская община и первые халифаты возникли в эпоху расцвета Танского Китая.'],
      ['Early Islam and the Tang Empire', 'The Muslim community and the first caliphates emerged during the flourishing of Tang China.'],
      ['早期伊斯兰与唐帝国', '穆斯林共同体与早期哈里发国兴起之时，唐代中国正处于繁荣阶段。'], ['met', 'asia']),
    insight('abbasids-charlemagne-world', 768, 814, ['islam', 'christianity'],
      ['Аббасиды и мир Карла Великого', 'Багдадский халифат и христианский Запад Каролингов создавали разные политические и интеллектуальные центры в одну эпоху.'],
      ['The Abbasids and Charlemagne’s world', 'The Baghdad caliphate and the Carolingian Christian West built different political and intellectual centers in the same era.'],
      ['阿拔斯与查理曼的世界', '巴格达哈里发国与加洛林基督教西方在同一时代形成了不同的政治和知识中心。'], ['met']),
    insight('baghdad-maya-classic', 750, 900, ['islam', 'maya'],
      ['Багдад и классические майя', 'Аббасидский Багдад рос как центр учёности, пока города классических майя процветали по другую сторону мира.'],
      ['Baghdad and the Classic Maya', 'Abbasid Baghdad grew as a center of learning while Classic Maya cities flourished across the world.'],
      ['巴格达与古典期玛雅', '阿拔斯时代的巴格达成长为学术中心时，世界另一端的古典期玛雅城市也在繁荣。'], ['met', 'smarthistory']),
    insight('viking-age-heian', 794, 1050, ['christianity', 'japan'],
      ['Христианская Европа и Хэйан', 'Викингская и христианская Европа менялась в те же века, когда японский двор Хэйан создавал собственную придворную культуру.'],
      ['Christian Europe and Heian Japan', 'Viking and Christian Europe changed during the same centuries that the Heian court shaped its own culture in Japan.'],
      ['基督教欧洲与平安时代', '维京与基督教欧洲发生变化的数百年间，日本平安朝廷也在塑造独特的宫廷文化。'], ['met', 'asia']),
    insight('song-china-mississippi', 1000, 1200, ['china', 'north_america'],
      ['Сунский Китай и Кахокия', 'Города Сунского Китая существовали одновременно с расцветом Кахокии и миссисипских обществ Северной Америки.'],
      ['Song China and Cahokia', 'The cities of Song China overlapped with the flourishing of Cahokia and Mississippian societies in North America.'],
      ['宋代中国与卡霍基亚', '宋代中国的城市与北美卡霍基亚及密西西比文化社会的繁荣处于同一时代。'], ['asia', 'smarthistory']),
    insight('byzantium-inca-beginnings', 1250, 1400, ['byzantium', 'inca'],
      ['Поздняя Византия и ранние инки', 'Поздневизантийский мир существовал одновременно с ростом раннего Куско в Андах.'],
      ['Late Byzantium and the early Inca', 'The late Byzantine world overlapped with the growth of early Cusco in the Andes.'],
      ['晚期拜占庭与早期印加', '晚期拜占庭世界存在之时，安第斯地区的早期库斯科也在成长。'], ['met', 'smarthistory']),
    insight('mongols-mali', 1235, 1400, ['steppe', 'west_africa'],
      ['Монголы и империя Мали', 'Монгольские державы связывали Евразию в те же века, когда империя Мали усиливалась в Западной Африке.'],
      ['The Mongols and the Mali Empire', 'Mongol states connected Eurasia while the Mali Empire grew in West Africa.'],
      ['蒙古与马里帝国', '蒙古诸国连接欧亚大陆之时，西非的马里帝国也在崛起。'], ['met', 'british']),
    insight('mansa-musa-yuan', 1271, 1368, ['west_africa', 'china'],
      ['Манса Муса и Юаньский Китай', 'Мали Мансы Мусы и Китай династии Юань были частью разных, но одновременно процветавших сетей Старого Света.'],
      ['Mansa Musa and Yuan China', 'Mansa Musa’s Mali and Yuan China belonged to different but simultaneously flourishing networks of the Old World.'],
      ['曼萨·穆萨与元代中国', '曼萨·穆萨统治下的马里与元代中国属于旧大陆中不同却同时繁荣的网络。'], ['british', 'asia']),
    insight('aztec-byzantium', 1325, 1453, ['aztec', 'byzantium'],
      ['Теночтитлан и Константинополь', 'Теночтитлан рос в Центральной Мексике, пока Константинополь оставался столицей поздней Византии.'],
      ['Tenochtitlan and Constantinople', 'Tenochtitlan grew in Central Mexico while Constantinople remained the capital of late Byzantium.'],
      ['特诺奇蒂特兰与君士坦丁堡', '特诺奇蒂特兰在墨西哥中部成长之时，君士坦丁堡仍是晚期拜占庭的首都。'], ['smarthistory', 'met']),
    insight('inca-ming', 1368, 1500, ['inca', 'china'],
      ['Инки и империя Мин', 'Империя инков расширялась в Андах в первые столетия правления династии Мин в Китае.'],
      ['The Inca and the Ming Empire', 'The Inca state expanded in the Andes during the first centuries of Ming rule in China.'],
      ['印加与明帝国', '印加国家在安第斯扩张之时，中国正处于明代统治的前几个世纪。'], ['smarthistory', 'asia']),
    insight('sikhism-aztec', 1469, 1521, ['sikhism', 'aztec'],
      ['Гуру Нанак и поздние ацтеки', 'Жизнь Гуру Нанака в Пенджабе началась в эпоху поздней Ацтекской империи в Центральной Мексике.'],
      ['Guru Nanak and the late Aztecs', 'Guru Nanak’s life in Punjab began during the era of the late Aztec Empire in Central Mexico.'],
      ['古鲁那纳克与晚期阿兹特克', '古鲁那纳克在旁遮普的一生开始于墨西哥中部晚期阿兹特克帝国的时代。'], ['asia', 'smarthistory']),
    insight('jainism-buddhism', -500, 300, ['jainism', 'buddhism'],
      ['Джайнизм и ранний буддизм', 'Джайнские и буддийские общины развивали разные пути освобождения в общей среде древней Южной Азии.'],
      ['Jainism and early Buddhism', 'Jain and Buddhist communities developed distinct paths to liberation within the shared world of ancient South Asia.'],
      ['耆那教与早期佛教', '耆那教与佛教社群在古代南亚共同的思想环境中发展出不同的解脱道路。'], ['asia']),
    insight('zoroastrianism-judaism', -600, 500, ['zoroastrianism', 'judaism'],
      ['Зороастризм и иудаизм', 'Иранская и иудейская религиозные традиции развивались рядом во времени в имперских мирах Западной Азии.'],
      ['Zoroastrianism and Judaism', 'Iranian and Jewish religious traditions developed alongside one another in the imperial worlds of West Asia.'],
      ['祆教与犹太教', '伊朗与犹太宗教传统在西亚帝国世界中相近的历史时期发展。'], ['met']),
    insight('manichaeism-christianity', 240, 600, ['manichaeism', 'christianity'],
      ['Манихейство и христианство', 'Манихейские миссии распространялись по Евразии в эпоху формирования имперских христианских церквей.'],
      ['Manichaeism and Christianity', 'Manichaean missions spread across Eurasia while imperial Christian churches were taking shape.'],
      ['摩尼教与基督教', '摩尼教传教活动横跨欧亚之时，帝国基督教会也正在形成。'], ['met', 'asia']),
    insight('daoism-roman-religion', -300, -100, ['daoism', 'roman_religion'],
      ['Даосские тексты и римские культы', 'Ранние даосские тексты и общины складывались в Китае в столетия республиканской и имперской религии Рима.'],
      ['Daoist texts and Roman cults', 'Early Daoist texts and communities took shape in China during the centuries of Republican and Imperial Roman religion.'],
      ['道教文本与罗马祭祀', '早期道家文本与社群在中国形成的数百年，也正值罗马共和国与帝国宗教发展的时代。'], ['asia', 'met']),
    insight('shinto-maya', 700, 900, ['shinto', 'maya'],
      ['Японские ками и классические майя', 'Японские храмовые практики и города классических майя развивались одновременно в далёких частях мира.'],
      ['Japanese kami and the Classic Maya', 'Japanese shrine practices and Classic Maya cities developed at the same time in distant parts of the world.'],
      ['日本神祇与古典期玛雅', '日本神社实践与古典期玛雅城市在世界相距遥远的地区同时发展。'], ['asia', 'smarthistory']),
    insight('andean-mesoamerican-ritual', -900, 900, ['andean_religion', 'mesoamerican_religion'],
      ['Ритуальные миры Америк', 'Горные святилища Анд и храмовые центры Мезоамерики развивали разные ритуальные традиции задолго до европейского контакта.'],
      ['Ritual worlds of the Americas', 'Andean mountain sanctuaries and Mesoamerican temple centers developed distinct ritual traditions long before European contact.'],
      ['美洲的仪式世界', '安第斯山地圣所与中部美洲神庙中心在欧洲人到来之前很久便发展出不同的仪式传统。'], ['smarthistory'])
  ];
}));
